name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Connect to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x4t7e1f4
    
    - name: Build the Docker image
      run: |
           docker build -t 002891/cicd-flask-image .
           docker tag cicd-flask-image:latest public.ecr.aws/x4t7e1f4/002891/cicd-flask-image:latest
           docker push public.ecr.aws/x4t7e1f4/002891/cicd-flask-image:latest
